# -*- coding: utf-8 -*-
"""Fakenews.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j3GBZnw5u43AGytzhXKQ0msWKGMOXkRn
"""

import pandas as pd
from google.colab import files

uploaded = files.upload()

data = pd.read_csv("news_articles.csv")

data.head()

missing_values_rows = data.isnull().any(axis=1)
print("Rows with Missing Values:")
print(missing_values_rows)

duplicate_rows = data[data.duplicated()]
print("Duplicated Rows:")
print(duplicate_rows)

data.dropna(axis=0, inplace=True)

data.drop_duplicates(inplace=True)

data.to_csv("cleaned_dataset.csv", index=False)

file_path = "cleaned_dataset.csv"
files.download(file_path)